### ISSUE TITLE
logger configuration

### ISSUE THREAD

**Issue by qamatic** [qamatic/mintleaf#1]
need to introduce logger configuration with slf / log4j.   There is a logger abstract and console logger already in the framework but someone needs to wire up based on the choice of the user either slf / log4j.  so look out for MintleafLogger.java

**Comment by codewrox** [comment]
Got fixed.  Now you have the ability to inject any type of logger of your choice either singleton or per class basis.   By default NoLogger is set but you can always override like the following:
 `MintleafLogger.setLoggerType(ConsoleLogger.class); `// ConsoleLogger is part of this framework
(OR)
 Implement your own logger type by extending this `class MintleafLogger` shown as below
For example:   
`public class Log4J extends MintleafLogger { 
 }`
and then set the logger type to be:
`MintleafLogger.setLoggerType(Log4J.class); `

So in your actual code where you require logger to be used as follows:
private static final MintleafLogger logger = MintleafLogger.getLogger(MyClass.class);

**Comment by qamatic** [comment]
Got fixed in 1.8.41. Now you have the ability to inject any type of logger of your choice either singleton or per class basis. By default NoLogger is set but you can always override like the following:
`MintleafLogger.setLoggerType(ConsoleLogger.class); `// ConsoleLogger is part of this framework
(OR)
Implement your own logger type by extending this `class MintleafLogger` shown as below
For example:
`public class Log4J extends MintleafLogger { }`
and then set the logger type to be:
`MintleafLogger.setLoggerType(Log4J.class); `

So in your actual code where you require logger to be used as follows:
private static final MintleafLogger logger = MintleafLogger.getLogger(MyClass.class);
